name: main

on:
  push:
    branches:
      - 'main'

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Shell
        timeout-minutes: 1
        env:
          WORKING_DIR: .
        run: |
          cd .
          echo hello
